site_name: U-16プログラミングコンテスト 釧路大会

theme:
  name: material
  language: ja
  repo: KPC-U16/CHaserRuleGuide-Pub

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - toc.integrate

  font:
    text: Kosugi Maru

  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

copyright: "&copy; 2024 oyasumi.ski"

