site_name: U-16プログラミングコンテスト 釧路大会

theme:
  name: material
  language: ja
  repo: KPC-U16/CHaserRuleGuide-Pub

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - navigation.top
    - toc.integrate
    - header.autohide

  font:
    text: Kosugi Maru

  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7

plugins:
  search:
    lang: "ja"


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

copyright: "&copy; 2024 U-16プログラミングコンテスト 釧路大会 実行委員会"

